#ifndef WINK_SDK_H
#define WINK_SDK_H

#ifdef __cplusplus
extern "C" {
#endif

/* Error handling */
const char *wink_last_error(void);
int wink_last_error_code(void);
int wink_error_count(void);
const char *wink_error_at(int index);
void wink_clear_errors(void);
int wink_run_catch(int (*func)(void));

/* Main SDK functions */
int wink_setup(const char *prefix);
int wink_run(const char *prefix, const char *exe, const char *args);
int wink_package(const char *dir, const char *output);
int wink_install_mono(const char *prefix);
int wink_install_gecko(const char *prefix);
int wink_run_winetricks(const char *prefix, const char *args);
int wink_set_registry(const char *prefix, const char *reg_file);
int wink_get_wine_version(char *buf, size_t buflen);
int wink_prefix_exists(const char *prefix);
int wink_delete_prefix(const char *prefix);
int wink_export_prefix(const char *prefix, const char *archive);
int wink_import_prefix(const char *archive, const char *prefix);
int wink_kill_processes();
int wink_run_dxvk_setup(const char *prefix);
int wink_cleanup_prefix(const char *prefix);
int wink_run_with_env(const char *prefix, const char *exe, const char *args, const char *env);
int wink_install_dotnet(const char *prefix);
int wink_install_vcrun(const char *prefix);
int wink_set_windows_version(const char *prefix, const char *version);
int wink_backup_registry(const char *prefix, const char *output);
int wink_restore_registry(const char *prefix, const char *input);
int wink_install_gallium_nine(const char *prefix);
int wink_setup_esync(const char *prefix);
int wink_setup_fsync(const char *prefix);
int wink_install_fonts(const char *prefix);
int wink_enable_virtual_desktop(const char *prefix, int width, int height);
int wink_disable_virtual_desktop(const char *prefix);
int wink_run_uninstaller(const char *prefix);
int wink_install_override_dll(const char *prefix, const char *dll);
int wink_remove_override_dll(const char *prefix, const char *dll);
int wink_run_config_script(const char *prefix, const char *script);
int wink_clean_cache(const char *prefix);
int wink_extract_msi(const char *prefix, const char *msi);
int wink_run_regsvr(const char *prefix, const char *dll);
int wink_set_cpu_cores(const char *prefix, int cores);
int wink_enable_pba(const char *prefix);
int wink_disable_pba(const char *prefix);
int wink_run_winecfg(const char *prefix);
int wink_run_explorer(const char *prefix, const char *path);
int wink_create_desktop_shortcut(const char *prefix, const char *name, const char *exe);
int wink_update_wine();
int wink_install_proton();
int wink_update_dxvk(const char *prefix);
int wink_self_update(const char *repo_dir);
int wink_prompt_update(const char *repo_dir);
int wink_list_processes();
int wink_terminate_process(const char *name);
int wink_install_game_msi(const char *prefix, const char *msi);
int wink_run_control_panel(const char *prefix);
int wink_get_winepath(const char *unix_path, char *out, size_t len);
int wink_get_native_path(const char *win_path, char *out, size_t len);
int wink_run_cmd(const char *prefix, const char *command);
int wink_fix_wineprefix(const char *prefix);
int wink_enable_hud(const char *prefix);
int wink_disable_hud(const char *prefix);


/* Winetricks helper wrappers */
#define WINK_DECLARE_VERB(name) int wink_##name(const char *prefix);
WINK_DECLARE_VERB(install_dxvk);
WINK_DECLARE_VERB(install_openal);
WINK_DECLARE_VERB(install_quartz);
WINK_DECLARE_VERB(install_msxml6);
WINK_DECLARE_VERB(install_physx);
WINK_DECLARE_VERB(install_xact);
WINK_DECLARE_VERB(install_directmusic);
WINK_DECLARE_VERB(install_d3dx9);
WINK_DECLARE_VERB(install_d3dcompiler);
WINK_DECLARE_VERB(install_wmp);
WINK_DECLARE_VERB(install_gstreamer);
WINK_DECLARE_VERB(install_vkd3d);
WINK_DECLARE_VERB(install_ffmpeg);
WINK_DECLARE_VERB(install_winhttp);
WINK_DECLARE_VERB(install_dotnet35);
WINK_DECLARE_VERB(install_mfc);
WINK_DECLARE_VERB(install_gdiplus);
WINK_DECLARE_VERB(install_msxml3);
WINK_DECLARE_VERB(install_msxml4);
WINK_DECLARE_VERB(install_vcrun6);
WINK_DECLARE_VERB(install_vcrun2005);
WINK_DECLARE_VERB(install_vcrun2008);
WINK_DECLARE_VERB(install_vcrun2010);
WINK_DECLARE_VERB(install_vcrun2012);
WINK_DECLARE_VERB(install_vcrun2013);
WINK_DECLARE_VERB(install_vcrun2015);
WINK_DECLARE_VERB(install_directplay);
WINK_DECLARE_VERB(install_dsound);
WINK_DECLARE_VERB(install_devenum);
WINK_DECLARE_VERB(install_shell32);
WINK_DECLARE_VERB(install_control_panel);
WINK_DECLARE_VERB(install_wininet);
WINK_DECLARE_VERB(install_comctl32);
WINK_DECLARE_VERB(install_riched20);
WINK_DECLARE_VERB(install_riched30);
WINK_DECLARE_VERB(install_secur32);
WINK_DECLARE_VERB(install_shlwapi);
WINK_DECLARE_VERB(install_urlmon);
WINK_DECLARE_VERB(install_advapi32);
WINK_DECLARE_VERB(install_winspool);
WINK_DECLARE_VERB(install_adobe_air);
WINK_DECLARE_VERB(install_flash);
WINK_DECLARE_VERB(install_chrome_frame);
WINK_DECLARE_VERB(install_d3d11);
WINK_DECLARE_VERB(install_dotnet452);
WINK_DECLARE_VERB(install_directx9);
WINK_DECLARE_VERB(install_directx10);
WINK_DECLARE_VERB(install_directx11);
WINK_DECLARE_VERB(install_physx_legacy);
WINK_DECLARE_VERB(install_3m_library);
WINK_DECLARE_VERB(install_7zip);
WINK_DECLARE_VERB(install_adobe_diged);
WINK_DECLARE_VERB(install_adobe_diged4);
WINK_DECLARE_VERB(install_autohotkey);
WINK_DECLARE_VERB(install_busybox);
WINK_DECLARE_VERB(install_cmake);
WINK_DECLARE_VERB(install_colorprofile);
WINK_DECLARE_VERB(install_controlpad);
WINK_DECLARE_VERB(install_controlspy);
WINK_DECLARE_VERB(install_dotnet20sdk);
WINK_DECLARE_VERB(install_dxsdk_aug2006);
WINK_DECLARE_VERB(install_dxsdk_jun2010);
WINK_DECLARE_VERB(install_dxwnd);
WINK_DECLARE_VERB(install_emu8086);
WINK_DECLARE_VERB(install_ev3);
WINK_DECLARE_VERB(install_firefox);
WINK_DECLARE_VERB(install_fontxplorer);
WINK_DECLARE_VERB(install_foobar2000);
WINK_DECLARE_VERB(install_hhw);
WINK_DECLARE_VERB(install_iceweasel);
WINK_DECLARE_VERB(install_irfanview);
WINK_DECLARE_VERB(install_kindle);
WINK_DECLARE_VERB(install_kobo);
WINK_DECLARE_VERB(install_mingw);
WINK_DECLARE_VERB(install_mozillabuild);
WINK_DECLARE_VERB(install_mpc);
WINK_DECLARE_VERB(install_mspaint);
WINK_DECLARE_VERB(install_mt4);
WINK_DECLARE_VERB(install_njcwp_trial);
WINK_DECLARE_VERB(install_njjwp_trial);
WINK_DECLARE_VERB(install_nook);
WINK_DECLARE_VERB(install_npp);
WINK_DECLARE_VERB(install_office2003pro);
WINK_DECLARE_VERB(install_office2007pro);
WINK_DECLARE_VERB(install_office2013pro);
WINK_DECLARE_VERB(install_ollydbg110);
WINK_DECLARE_VERB(install_ollydbg200);
WINK_DECLARE_VERB(install_ollydbg201);
WINK_DECLARE_VERB(install_openwatcom);
WINK_DECLARE_VERB(install_origin);
WINK_DECLARE_VERB(install_protectionid);
WINK_DECLARE_VERB(install_psdk2003);
WINK_DECLARE_VERB(install_psdkwin71);
WINK_DECLARE_VERB(install_qq);
WINK_DECLARE_VERB(install_qqintl);
WINK_DECLARE_VERB(install_safari);
WINK_DECLARE_VERB(install_sketchup);
WINK_DECLARE_VERB(install_steam);
WINK_DECLARE_VERB(install_ubisoftconnect);
WINK_DECLARE_VERB(install_utorrent);
WINK_DECLARE_VERB(install_utorrent3);
WINK_DECLARE_VERB(install_vc2005express);
WINK_DECLARE_VERB(install_vc2005expresssp1);
WINK_DECLARE_VERB(install_vc2005trial);
WINK_DECLARE_VERB(install_vc2008express);
WINK_DECLARE_VERB(install_vc2010express);
WINK_DECLARE_VERB(install_vlc);
WINK_DECLARE_VERB(install_vstools2019);
WINK_DECLARE_VERB(install_winamp);
WINK_DECLARE_VERB(install_winrar);
WINK_DECLARE_VERB(install_wme9);
WINK_DECLARE_VERB(install_3dmark03);
WINK_DECLARE_VERB(install_3dmark05);
WINK_DECLARE_VERB(install_3dmark06);
WINK_DECLARE_VERB(install_3dmark2000);
WINK_DECLARE_VERB(install_3dmark2001);
WINK_DECLARE_VERB(install_stalker_pripyat_bench);
WINK_DECLARE_VERB(install_unigine_heaven);
WINK_DECLARE_VERB(install_wglgears);
WINK_DECLARE_VERB(install_allcodecs);
WINK_DECLARE_VERB(install_amstream);
WINK_DECLARE_VERB(install_art2k7min);
WINK_DECLARE_VERB(install_art2kmin);
WINK_DECLARE_VERB(install_atmlib);
WINK_DECLARE_VERB(install_avifil32);
WINK_DECLARE_VERB(install_binkw32);
WINK_DECLARE_VERB(install_cabinet);
WINK_DECLARE_VERB(install_cinepak);
WINK_DECLARE_VERB(install_cmd);
WINK_DECLARE_VERB(install_cnc_ddraw);
WINK_DECLARE_VERB(install_comctl32ocx);
WINK_DECLARE_VERB(install_comdlg32ocx);
WINK_DECLARE_VERB(install_crypt32);
WINK_DECLARE_VERB(install_crypt32_winxp);
WINK_DECLARE_VERB(install_d3dcompiler_42);
WINK_DECLARE_VERB(install_d3dcompiler_43);
WINK_DECLARE_VERB(install_d3dcompiler_46);
WINK_DECLARE_VERB(install_d3dcompiler_47);
WINK_DECLARE_VERB(install_d3drm);
WINK_DECLARE_VERB(install_d3dx10);
WINK_DECLARE_VERB(install_d3dx10_43);
WINK_DECLARE_VERB(install_d3dx11_42);
WINK_DECLARE_VERB(install_d3dx11_43);
WINK_DECLARE_VERB(install_d3dx9_24);
WINK_DECLARE_VERB(install_d3dx9_25);
WINK_DECLARE_VERB(install_d3dx9_26);
WINK_DECLARE_VERB(install_d3dx9_27);
WINK_DECLARE_VERB(install_dotnet20);
WINK_DECLARE_VERB(install_dotnet30);
WINK_DECLARE_VERB(install_dotnet40);
WINK_DECLARE_VERB(install_dotnet45);
WINK_DECLARE_VERB(install_dotnet46);
WINK_DECLARE_VERB(install_dotnet461);
WINK_DECLARE_VERB(install_dotnet462);
WINK_DECLARE_VERB(install_dotnet471);
WINK_DECLARE_VERB(install_dotnet472);
WINK_DECLARE_VERB(install_vcrun2017);
WINK_DECLARE_VERB(install_vcrun2019);
WINK_DECLARE_VERB(install_vcrun2022);
WINK_DECLARE_VERB(install_wmp10);
WINK_DECLARE_VERB(install_wmp11);
WINK_DECLARE_VERB(install_wsh56);
WINK_DECLARE_VERB(install_wsh57);
WINK_DECLARE_VERB(install_wsh60);
WINK_DECLARE_VERB(install_wsh70);
WINK_DECLARE_VERB(install_wsh72);
WINK_DECLARE_VERB(install_faudio);
WINK_DECLARE_VERB(install_xna40);
WINK_DECLARE_VERB(install_d3dx9_28);
WINK_DECLARE_VERB(install_d3dx9_29);
WINK_DECLARE_VERB(install_d3dx9_30);
WINK_DECLARE_VERB(install_d3dx9_31);
WINK_DECLARE_VERB(install_d3dx9_32);
WINK_DECLARE_VERB(install_d3dx9_33);
WINK_DECLARE_VERB(install_d3dx9_34);
WINK_DECLARE_VERB(install_d3dx9_35);
WINK_DECLARE_VERB(install_d3dx9_36);
WINK_DECLARE_VERB(install_d3dx9_37);
WINK_DECLARE_VERB(install_d3dx9_38);
WINK_DECLARE_VERB(install_d3dx9_39);
WINK_DECLARE_VERB(install_d3dx9_40);
WINK_DECLARE_VERB(install_d3dx9_41);
WINK_DECLARE_VERB(install_d3dx9_42);
WINK_DECLARE_VERB(install_d3dx9_43);
WINK_DECLARE_VERB(install_ie6);
WINK_DECLARE_VERB(install_ie7);
WINK_DECLARE_VERB(install_ie8);
WINK_DECLARE_VERB(install_quicktime);
WINK_DECLARE_VERB(install_xvid);
WINK_DECLARE_VERB(install_wmv9vcm);
WINK_DECLARE_VERB(install_l3codecx);
WINK_DECLARE_VERB(install_mdac27);
WINK_DECLARE_VERB(install_mdac28);
WINK_DECLARE_VERB(install_msls31);
WINK_DECLARE_VERB(install_dinput8);
WINK_DECLARE_VERB(install_dinput);
WINK_DECLARE_VERB(install_dxdiag);

#undef WINK_DECLARE_VERB

#ifdef __cplusplus
}
#endif

#endif /* WINK_SDK_H */
